#!/bin/bash 
set -x
echo "Building the RESTfullStorageAPI" 
export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/home/dishan/tools/mongo-c-driver/lib/pkgconfig 
#g++ -Wall -std=c++0x ./src/MongoDbAdapter.cpp -o MongoDbAdapter $(pkg-config --cflags --libs libmongocxx) -Wl,-rpath /home/dishan/tools/mongo-c-driver/lib
g++ -c -Wall -Werror -fpic -std=c++0x -I/usr/include/cppconn ./src/Main.cpp  ./src/Request.cpp ./src/Base64.cpp ./src/RequestHandler.cpp ./src/HashUtil.cpp ./src/Entities/User.cpp ./src/MySqlDbAdapter.cpp ./src/MongoDbAdapter.cpp ./src/Commands/CreateSchemaCommand.cpp $(pkg-config --cflags --libs libmongocxx) 
#-Wl,-rpath /home/dishan/tools/mongo-c-driver/lib
g++ -shared -o libRESTfullStorageAPI.so Main.o Request.o RequestHandler.o Base64.o HashUtil.o User.o MySqlDbAdapter.o CreateSchemaCommand.o MongoDbAdapter.o -lssl -lcrypto -L/usr/lib -lmysqlcppconn $(pkg-config --cflags --libs libmongocxx) -Wl,-rpath /home/dishan/tools/mongo-c-driver/lib

