#!/bin/bash 
set -x
clear
rm -r *.o
rm -r *.so
echo "Building the RESTfullStorageAPI" 
export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/home/dishan/tools/mongo-c-driver/lib/pkgconfig 
echo "Building...."
g++ -c -Wall -Werror -fpic -std=c++0x -I/usr/include/cppconn -IInclude -IInclude/json -IInclude/Commands -IInclude/Entities ./src/Commands/* ./src/Entities/* ./src/*  $(pkg-config --cflags --libs libmongocxx) 
echo "Linking...."
g++ -shared -o libRESTfullStorageAPI.so *.o -lssl -lcrypto -L/usr/lib -lmysqlcppconn $(pkg-config --cflags --libs libmongocxx) -Wl,-rpath /home/dishan/tools/mongo-c-driver/lib

